project:
  type: book

book:
  title: "Fundamentos De Proximidad"
  author: 
    - name: "Arlet Pinacho Báez"
    - name: "Isaac Giovani Escobar Gónzalez"
    - name: "Kevin Jonathan Garduño Escobar"
    - name: "Seldon Sautto Ramírez"
  date: "22/5/2026"
  chapters:
    - index.qmd
    - fundamentos.qmd
    - distancias.qmd
    - coseno.qmd
    - normalizacion.qmd
    - references.qmd

bibliography: references.bib

nocite: |
  @*

format:
  html:
    code-fold: true
    html-math-method: mathjax
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt


