project:
  type: book

book:
  title: "Fundamentos De Proximidad"
  author: "Arlet Pinacho Báez, 
   Isaac Giovani Escobar Gónzalez,
   Kevin Jonathan Garduño Escobar,
   Seldon Sautto Ramírez"
  date: "22/5/2026"
  chapters:
    - index.qmd
    - fundamentos.qmd
    - distancias.qmd
    - coseno.qmd
    - normalizacion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-fold: true
    html-math-method: mathjax
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



